name: Continuous Integration for Website

on:
  pull_request:
    branches: [ "main" ]
    paths:
    - 'htmt/**'

defaults:
  run:
    shell: bash
    working-directory: ./src

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
# Builds the documentation website
  deploy-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Deploy website
        run: dotnet run --project HtmlTemplater.CLI -- ../htmt/manifest.json
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/'
